### ISSUE TITLE
Background colour options for dark and light 

### ISSUE THREAD

**Issue by kmaustral** [reorx/obsidian-daily-notes-new-tab#1]
This plugin helps greatly to make Daily Notes a key part of the daily workflow. I like being able to distinguish the pane with background colour. However, because I change between dark and light themes during the day, I have to alter the background colour each time as well. It would be great if there were two options for this, one for dark and one for light.

**Comment by reorx** [comment]
Sure, it's doable, on my way

**Comment by reorx** [comment]
Added the new background color dark option in [release 1.2.0](https://github.com/reorx/obsidian-daily-notes-new-tab/releases/tag/1.2.0):
![image](https://user-images.githubusercontent.com/405972/157439142-0fdabf9c-13c4-41ab-aadd-b7701dd2bffd.png)

You can upgrade the plugin and check if it works or not.

If you think it's helpful, feel free to leave a comment in the [forum thread](https://forum.obsidian.md/t/plugin-for-opening-daily-notes-in-new-tab-and-much-more/33698) ☺️

**Comment by kmaustral** [comment]
Works perfectly! Well done.
