### ISSUE TITLE
[Feature Request] Support for weekly, monthly, quarterly, and yearly notes

### ISSUE THREAD

**Issue by yutaizhou** [reorx/obsidian-daily-notes-new-tab#3]
This is a great plugin that solves a common annoying problem in Obsidian. I think it would make sense to extend its functionalities to the other types of periodic notes as well!

**Comment by reorx** [comment]
I've considered that, but for me, only daily notes are used very frequently. I'm glad to make new integrations with other periodic notes, but because my schedule is tight, could you tell me which one you needed most? I can get started with that in a day or two.

**Comment by reorx** [comment]
Additionally, I'm planning to adapt the functionality of [Lumberjack](https://github.com/ryanjamurphy/lumberjack-obsidian), to make a command that not only opens the daily note but also append a bullet with a time prefix so that you can start to record the journal instantly, any suggestions?

**Comment by yutaizhou** [comment]
That lumberjack feature sounds pretty great, though I haven't quite experienced that use case before. 

As for the periodic note integration, weekly note is a pretty frequent one for me!

**Comment by reorx** [comment]
Hi @yutaizhou, I just released [1.3.0](https://github.com/reorx/obsidian-daily-notes-new-tab/releases/tag/1.3.0) that adds support for weekly notes, please have a look. If you find any problem just reply to this issue.
