### ISSUE TITLE
Problem with background

### ISSUE THREAD

**Issue by pcause** [reorx/obsidian-daily-notes-new-tab#6]
I use periodic notes and the topaz theme.  I open style settings and I don't see a way to change the background for periodic notes, as you suggest in the settings for the plugin.  Can you either clarify or have an option NOT to override theme background setting.  Thanks.

**Comment by reorx** [comment]
Hi, I just released [1.5.0](https://github.com/reorx/obsidian-daily-notes-new-tab/releases/tag/1.5.0), which allows you to disable the background customizing feature, please update and try if it helps.

> I open style settings and I don't see a way to change the background for periodic notes, as you suggest in the settings for the plugin

Do you mean you cannot see this? 
<img width="771" alt="image" src="https://user-images.githubusercontent.com/405972/161997255-9f7abcce-44b4-4bfa-a969-18fb07ebadec.png">

**Comment by pcause** [comment]
no i dont.  which section of the style settings is that in.  I dont see it at all.

**Comment by reorx** [comment]
Oh, I see, this is part of another plugin called [Style Settings](https://github.com/mgmeyers/obsidian-style-settings), you need to install it first, and then open its settings to see the color customization.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/405972/162000649-5550b3c8-4930-419a-99bc-8e9e7bb5c009.png">

**Comment by pcause** [comment]
I have styule settings installed.  This is what I see when opening.  I am on latest insider build

![image](https://user-images.githubusercontent.com/1071479/162001425-8af0b485-9c85-4204-8c6b-b03a9dd977d0.png)

**Comment by reorx** [comment]
This is very weird, could you try to disable the style settings plugin and then enable it again?

**Comment by pcause** [comment]
that did it.  I now see the option

![image](https://user-images.githubusercontent.com/1071479/162002276-4dc60d64-6c29-4efa-81a1-b994da69de92.png)

**Comment by pcause** [comment]
still think there should be an option NOT to change the background.

**Comment by reorx** [comment]
I'm glad it works!

> Hi, I just released [1.5.0](https://github.com/reorx/obsidian-daily-notes-new-tab/releases/tag/1.5.0), which allows you to disable the background customizing feature, please update and try if it helps.

Check this line I mentioned above, the new settings are like this:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/405972/162003051-a780b364-7afc-4989-a266-15dc5707bc28.png">

**Comment by pcause** [comment]
downloaded and it worked.  before, without this, i had set backgroun d to black.  it didn't work.  and, ALL of the colors and things seemed modified.  but this works for me now.  thanks
