### ISSUE TITLE
[feature request] option to pin the daily note

### ISSUE THREAD

**Issue by pcause** [reorx/obsidian-daily-notes-new-tab#7]
Could you add an option to pin the daily note when opening?  I use the tabs plugin and like to keep my daily note always open

**Comment by reorx** [comment]
I could, but I'm wondering whether this option is necessary. In my understanding, if you want the daily note to be pinned, you possibly don't want to close it, in that case pinning the note is a low-frequency action, no need to bind with the open note action.

My workflow uses a different approach, I never keep the daily note open for long term, I use the keyboard shortcut (`⌘ ;`) to open the daily note when I want to record something, and immediately close it after finishing recording. Sometimes I forget to close it, the plugin will focus on the already opened one to avoid redundancy. This is the original motivation I made this plugin.

**Comment by pcause** [comment]
yes, certainly.  i'll close becuase it is easy to take another approach.
