### ISSUE TITLE
cannot find backgroud color setting in Style Settings

### ISSUE THREAD

**Issue by wiley7** [reorx/obsidian-daily-notes-new-tab#8]
cannot find backgroud color setting in Style Settings

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/1320812/162880820-7e2b6bc5-1f29-4b13-9b2d-c60dfc21d93f.png">
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/1320812/162880859-c88ea20b-f1b5-4af5-95a1-09f80378d24d.png">

**Comment by reorx** [comment]
Try to disable then enable the Style Settings plugin, see the similar issue https://github.com/reorx/obsidian-daily-notes-new-tab/issues/6#issuecomment-1090356810

**Comment by wiley7** [comment]
it works!  thanks 🤟
